name: tugas_modul3
description: A Flutter demo flower shop app with Midtrans sandbox payment.
publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.0  # ðŸ†• Untuk TUGAS 2: Perbandingan HTTP vs Dio
  
  # Local Storage
  shared_preferences: ^2.2.3  # TUGAS 3: Data sederhana
  hive: ^2.2.3                # TUGAS 3: Data terstruktur
  hive_flutter: ^1.1.0
  
  # Cloud Storage
  supabase_flutter: ^2.3.4    # TUGAS 3: Auth & Database
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # Location Services
  geolocator: ^14.0.2         # TUGAS 4: GPS, Network, Live Location
  
  # Maps
  flutter_map: ^8.2.2         # TUGAS 4: OpenStreetMap
  latlong2: ^0.9.1
  
  # Utilities
  intl: ^0.19.0               # ðŸ†• Untuk formatting
  uuid: ^4.5.0
  
  # âœ… MODUL 6: Firebase & Push Notification
  firebase_core: ^4.2.1       # Firebase core library
  firebase_messaging: ^16.0.4 # Push notification via FCM
  flutter_local_notifications: ^17.2.3 # Local notification display


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - .env
